
# username: 您的的用户名(一般是手机号码)
username: ""

# password: 密码
password: ""

# date: 挂号日期
date: "2018-08-03"


# hospitalId: 医院id
hospitalId: "34"

# departmentId: 科室id  牙科：200004185
departmentId: "200004185"

# 关于如何获取 hospitalId 和 departmentId
# 1. 打开挂号页面
# 2. 假设地址栏中地址是 http://www.bjguahao.gov.cn/dpt/appoint/162-200002248.htm
# 3. 其中 162 是 hospitalId
# 4. 其中 200002248 是 departmentId


# 需要挂早上的号请填写1  需要挂下午的号请填写2
dutyCode: "1"

# patientName: 患者姓名
# 若是自己挂号可为空
patientName: ""

# childrenName：患儿姓名
# 若非儿科可为空
childrenName: ""

# childrenBirthday：患儿生日
# 若非儿科可为空
childrenBirthday: ""

# childrenGender：患儿性别 男(1) 女(2)
# 若非儿科可为空
childrenGender: ""

# doctorName: 医生姓名
# 不填写的话默认选最好的医生
# 填写后若这个医生没有号，会自动选其余号中最好的医生
doctorName: ""

# DebugLevel: 调试等级
# 支持的调试等级有 debug/info/warning/error/critical
DebugLevel: "info"

#使用ios短信和mac电脑接收验证码
useIMessage: "false"

# 是否使用 QPython3.6 运行本脚本
useQPython3: "true"
